POST http://localhost:8002/oauth/token
Content-Type: application/json

{
    "grant_type":    "password",
    "client_id":     2,
    "client_secret": "",
    "scope":         "*",
    "username":      "butko1991@gmail.com",
    "password":      ""
}
